# Generated by Django 4.2.10 on 2024-02-18 03:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cv', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('experience', models.CharField(default='1 năm', max_length=255, null=True)),
                ('expirationDate', models.DateField()),
                ('description', ckeditor.fields.RichTextField(blank=True, default='BCS', null=True)),
                ('quantity', models.IntegerField(default='1', null=True)),
                ('sex', models.CharField(default='ABC', max_length=50, null=True)),
                ('workingForm', models.CharField(default='ABC', max_length=255, null=True)),
                ('carrer', models.CharField(default='ABC', max_length=255, null=True)),
                ('area', models.CharField(default='ABC', max_length=255, null=True)),
                ('wage', models.CharField(default='ABC', max_length=255, null=True)),
                ('position', models.CharField(default='ABC', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
