# Generated by Django 4.2.10 on 2024-02-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_career_applicant_applicant_career_and_more'),
        ('jobs', '0003_remove_recruitmentpost_carrer_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentpost',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.career'),
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
