# Generated by Django 4.2.10 on 2024-02-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_recruitmentpost_career_delete_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentpost',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentpost',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
