# Generated by Django 4.2.10 on 2024-02-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobapplication_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentpost',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
