# Generated by Django 4.2.10 on 2024-02-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_recruitmentpost_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cv',
        ),
    ]
