# Generated by Django 4.2.10 on 2024-02-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_jobapplication_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='coverLetter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
