# Generated by Django 4.2.10 on 2024-02-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobapplication_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='testdate',
            field=models.DateTimeField(null=True),
        ),
    ]
