# Generated by Django 4.2.10 on 2024-02-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_auth_provider'),
        ('jobs', '0015_alter_recruitmentpost_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentpost',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employer'),
        ),
    ]
