# Generated by Django 4.2.10 on 2024-02-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_jobapplication_id_alter_recruitmentpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentpost',
            name='id',
            field=models.SlugField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
