# Generated by Django 4.2.10 on 2024-02-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_recruitmentpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
