# Generated by Django 4.2.10 on 2024-02-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_recruitmentpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
