# Generated by Django 4.2.10 on 2024-02-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_applicant_career_career_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='applicant',
        ),
        migrations.AddField(
            model_name='applicant',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.career'),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
