# Generated by Django 4.2.10 on 2024-02-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.FileField(null=True, upload_to='users/cv'),
        ),
    ]
