# Generated by Django 4.2.10 on 2024-02-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employer_unique_together_rating_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='applicant',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('applicant', 'lesson')},
        ),
    ]
