# Generated by Django 4.2.10 on 2024-02-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_user_comment_applicant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='lesson',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='lesson',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='lesson',
            new_name='employer',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('applicant', 'employer')},
        ),
    ]
