# Generated by Django 4.2.10 on 2024-02-23 14:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_lesson_comment_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cv'),
        ),
    ]
