# Generated by Django 4.2.10 on 2024-02-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_image_alter_applicant_cv'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('applicant', 'employer')},
        ),
    ]
