# Generated by Django 4.2.10 on 2024-02-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
