# Generated by Django 4.2.10 on 2024-02-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_applicant_id_alter_employer_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='workingForm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.SlugField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=models.SlugField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.SlugField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
