# Generated by Django 4.2.10 on 2024-02-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_applicant_workingform_alter_applicant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
