# Generated by Django 4.2.10 on 2024-02-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_applicant_id_alter_employer_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='areas',
            field=models.ManyToManyField(blank=True, to='users.area'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='wage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
